sudo: required
services:
  - docker
language: python
cache: pip
python:
 - "3.6"
 - "3.5"
 - "3.4"
 - "2.7"
 - "pypy"
env:
  - TEST_PIP_VERSION="<10.0"
  - TEST_PIP_VERSION=""
install:
  - "pip install tox tox-travis"
script:
  - "tox --force-dep pip$TEST_PIP_VERSION"
notifications:
  email: false
