sudo: required
services:
  - docker
language: python
cache: pip
python:
 - "3.6"
 - "3.5"
 - "3.4"
 - "2.7"
 - "pypy"
env:
  - TEST_PIP_VERSION="<10.0"
  - TEST_PIP_VERSION=""
install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
  - "pip install tox tox-travis"
  - "pip install --force-reinstall pip$TEST_PIP_VERSION"
script:
  - "tox"
notifications:
  email: false
